export {default as Nav} from './navbar/NavBar'
export {default as HomeHeader} from './header/home/HomeHeader'
export {default as Slider} from './slider/home/Slider'
export {default as HomeHaveYouEver} from './components/home/HomeHaveYouEver'
export {default as CTA} from './CTA/CTA'
export {default as UseCases} from './usecases/UseCases'
export {default as Footer} from './footer/Footer'
