export {default as Nav} from './navbar/NavBar'
export {default as HomeHeader} from './header/home/HomeHeader'
export {default as Slider} from './slider/home/Slider'
export {default as HomeHaveYouEver} from './components/home/HomeHaveYouEver'
export {default as CTA} from './CTA/CTA'
export {default as UseCases} from './usecases/UseCases'
export {default as Footer} from './footer/Footer'
export {default as UnlockThePower} from './components/home/UnlockThePower'
export {default as WingsSection} from './components/home/WingsSection'
export {default as Contact} from './components/contactUs/Contact'
export {default as AboutUsSection} from './components/aboutUs and derived/AboutUsSection'
export {default as NoPageComponent} from './components/noPage/NoPageComponent'
export {default as TermsOfServiceSection} from './components/aboutUs and derived/TermsOfServiceSection'
export {default as PrivacyPolicy} from './components/aboutUs and derived/PrivacyPolicy'
export {default as InfoSection} from './components/home/InfoSection'
